"""Shared error codes/messages for the EVM JSON-RPC wrapper."""

from __future__ import annotations

RPC_URL_REQUIRED_MESSAGE = "couldnt find an rpc url. give me an rpc url so i can add it to env."

ERR_INVALID_REQUEST = "INVALID_REQUEST"
ERR_METHOD_NOT_IN_MANIFEST = "METHOD_NOT_IN_MANIFEST"
ERR_METHOD_DISABLED = "METHOD_DISABLED"
ERR_POLICY_DENIED = "POLICY_DENIED"
ERR_RPC_URL_REQUIRED = "RPC_URL_REQUIRED"
ERR_RPC_TRANSPORT = "RPC_TRANSPORT_ERROR"
ERR_RPC_TIMEOUT = "RPC_TIMEOUT"
ERR_RPC_REMOTE = "RPC_REMOTE_ERROR"
ERR_ADAPTER_VALIDATION = "ADAPTER_VALIDATION_FAILED"

# Broadcast-specialized remote error codes.
ERR_RPC_BROADCAST_NONCE_TOO_LOW = "RPC_BROADCAST_NONCE_TOO_LOW"
ERR_RPC_BROADCAST_ALREADY_KNOWN = "RPC_BROADCAST_ALREADY_KNOWN"
ERR_RPC_BROADCAST_UNDERPRICED = "RPC_BROADCAST_UNDERPRICED"
ERR_RPC_BROADCAST_INSUFFICIENT_FUNDS = "RPC_BROADCAST_INSUFFICIENT_FUNDS"
ERR_INTERNAL = "INTERNAL_ERROR"
