"""Shared error codes/messages for the EVM JSON-RPC wrapper."""

from __future__ import annotations

# Deprecated in 2026-02-08 (default-pool RPC resolution), retained for backward compatibility.
RPC_URL_REQUIRED_MESSAGE = "couldnt find an rpc url. give me an rpc url so i can add it to env."

ERR_INVALID_REQUEST = "INVALID_REQUEST"
ERR_METHOD_NOT_IN_MANIFEST = "METHOD_NOT_IN_MANIFEST"
ERR_METHOD_DISABLED = "METHOD_DISABLED"
ERR_POLICY_DENIED = "POLICY_DENIED"
ERR_RPC_URL_REQUIRED = "RPC_URL_REQUIRED"
ERR_RPC_TRANSPORT = "RPC_TRANSPORT_ERROR"
ERR_RPC_TIMEOUT = "RPC_TIMEOUT"
ERR_RPC_REMOTE = "RPC_REMOTE_ERROR"
ERR_ADAPTER_VALIDATION = "ADAPTER_VALIDATION_FAILED"
ERR_LOGS_RANGE_TOO_LARGE = "LOGS_RANGE_TOO_LARGE"
ERR_LOGS_TOO_MANY_RESULTS = "LOGS_TOO_MANY_RESULTS"
ERR_LOGS_ENGINE_FAILED = "LOGS_ENGINE_FAILED"
ERR_INVALID_LOG_ADDRESS = "INVALID_LOG_ADDRESS"
ERR_INVALID_TOPIC_FORMAT = "INVALID_TOPIC_FORMAT"
ERR_INVALID_TOPIC_LENGTH = "INVALID_TOPIC_LENGTH"
ERR_INVALID_BLOCK_RANGE = "INVALID_BLOCK_RANGE"
ERR_TRACE_UNSUPPORTED = "TRACE_UNSUPPORTED"
ERR_SIMULATION_REVERTED = "SIMULATION_REVERTED"
ERR_ABI_ENCODE_FAILED = "ABI_ENCODE_FAILED"
ERR_ABI_DECODE_FAILED = "ABI_DECODE_FAILED"
ERR_MULTICALL_PARTIAL_FAILURE = "MULTICALL_PARTIAL_FAILURE"

# Broadcast-specialized remote error codes.
ERR_RPC_BROADCAST_NONCE_TOO_LOW = "RPC_BROADCAST_NONCE_TOO_LOW"
ERR_RPC_BROADCAST_ALREADY_KNOWN = "RPC_BROADCAST_ALREADY_KNOWN"
ERR_RPC_BROADCAST_UNDERPRICED = "RPC_BROADCAST_UNDERPRICED"
ERR_RPC_BROADCAST_INSUFFICIENT_FUNDS = "RPC_BROADCAST_INSUFFICIENT_FUNDS"
ERR_INTERNAL = "INTERNAL_ERROR"
